In [15]:
#coding:utf-8
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import operator
def sign(vec):
    if vec >= 0:
        return 1
    else:
        return -1
p_x=np.array([[1,0,1,1],[0,1,1,1],[1,1,0,1],[0,1,0,1]])#四个样本的增值模式 
p_y=np.array([1,1,-1,-1])#对应类别1表示w1类，-1表示为w2类
plt.figure()
ax1=plt.subplot(211,projection='3d')
ax1.set_title('sample scatter diagram')
ax2=plt.subplot(2,1,2)
ax2.set_title('percetron')
ax2.set_xlabel('iteration')  #为子图设置横轴标题
ax2.set_ylabel('weight_w')    #为子图设置纵轴标题
for i in range(len(p_x)):
    if p_y[i]==1:
        ax1.scatter(p_x[0,i],p_x[1,i],p_x[2,i], s=50)#显示w1类数据
    else :
        ax1.scatter(p_x[0,i],p_x[1,i],p_x[2,i], marker='x',s=50)#显示w2类数据
w=np.array([1,1,1,1])
b=0
delta=1
w0=0;
W=[]#用于存储每次更新的w
for i in range(1,5):
    print("第%d次迭代："%i)
    for j in range(len(p_x)):
        if p_y[j]*np.dot(w,p_x[j])<=0:#判断是否分错类
            w=w+delta*p_x[j]*p_y[j]#更新权值
            w0=i#存储迭代次数
        print(w)
    W.append(w.tolist())#将每次更新的w存储到W中
print("经过%d次迭代后，样本有收敛解"%w0)
print("此时权值为%s"%w)
W=np.array(W)
plt.sca(ax2)
W1=(W[:,0])
W2=(W[:,1])
W3=(W[:,2])
W4=(W[:,3])
t=[1,2,3,4]
plt.plot(t,W1)
plt.plot(t,W2)
plt.plot(t,W3)
plt.plot(t,W4)
plt.show()



    



第1次迭代：
[1 1 1 1]
[1 1 1 1]
[0 0 1 0]
[ 0 -1  1 -1]
第2次迭代：
[ 1 -1  2  0]
[ 1 -1  2  0]
[ 0 -2  2 -1]
[ 0 -2  2 -1]
第3次迭代：
[ 0 -2  2 -1]
[ 0 -1  3  0]
[ 0 -1  3  0]
[ 0 -1  3  0]
第4次迭代：
[ 0 -1  3  0]
[ 0 -1  3  0]
[ 0 -1  3  0]
[ 0 -1  3  0]
经过3次迭代后，样本有收敛解
此时权值为[ 0 -1  3  0]
